theme: jekyll-theme-minimal
title: Finding Fit
description: A small blog website for PE 1 A.Y. 2020-2021 2nd Trimester
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: About Me
    url: about
  - title: Journey
    url: journey
  - title: Fitness Index Charts
    url: references
