theme: jekyll-theme-minimal
title: trial for mms142
description: Using a simple template based on minimal jekyll theme
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: About Us
    url: about
  - title: Report
    url: report
